### ISSUE TITLE
LoadException

### ISSUE THREAD

**Issue by icode** [uchuhimo/konf#24]
```
Exception in thread "main" com.uchuhimo.konf.source.LoadException: fail to load web.host
	at com.uchuhimo.konf.source.SourceKt.loadItem(Source.kt:748)
	at com.uchuhimo.konf.source.SourceKt$load$$inlined$apply$lambda$1.invoke(Source.kt:756)
	at com.uchuhimo.konf.source.SourceKt$load$$inlined$apply$lambda$1.invoke(Source.kt)
	at com.uchuhimo.konf.BaseConfig.lock(BaseConfig.kt:62)
	at com.uchuhimo.konf.source.SourceKt.load(Source.kt:754)
	at com.uchuhimo.konf.BaseConfig.addSource(BaseConfig.kt:464)
	at com.uchuhimo.konf.Config$DefaultImpls.withSource(Config.kt:249)
	at com.uchuhimo.konf.BaseConfig.withSource(BaseConfig.kt:47)
	at com.uchuhimo.konf.source.Loader.resource(Loader.kt:264)
	at com.sinitek.data.server.ConfigKt.classpath(Config.kt:36)
	at com.sinitek.data.server.Configuration.load(Config.kt:57)
	at com.sinitek.data.server.ApplicationKt.main(Application.kt:7)
Caused by: com.uchuhimo.konf.source.NoSuchPathException: cannot find path "host" in source [type: value, url: file:/home/icode/projects/data-center/server/build/resources/main/config.yml, resource: config.yml]
	at com.uchuhimo.konf.source.base.ValueSource.getOrNull(ValueSource.kt:61)
	at com.uchuhimo.konf.source.base.MapSource.getOrNull(MapSource.kt:50)
	at com.uchuhimo.konf.source.SourceKt.loadItem(Source.kt:734)
	... 11 more
```

please ignore not exist file, and ignore config file not exist key

**Comment by feature** [comment]
Can you provide the code for you config, the code you use for loading, and the config files? The stacktrace gives a good idea of what might be wrong, but it's hard to help when we don't have much context.
