### ISSUE TITLE
No support for having no prefix?

### ISSUE THREAD

**Issue by golx** [uchuhimo/konf#41]
Hello,

Say I have the following set of existing environment variables within my infrastructure:
```
DATABASE=foo.example.com
DATABASE_USER=john
DATABASE_PASS=doe
```

I want to, without modifying them, be able to resolve these variables from both YAML file and environment variables, with latter having precedence.

It seems that such naming is discouraged by `konf`.

I tried the following:
```
object Root : ConfigSpec("") {
    val DATABASE by required<String>()
    val DATABASE_USER by required<String>()
    val DATABASE_PASS by required<String>()
}

Config {
    addSpec(Root)
}
        .from.yaml.resource("server.yml")
        .from.env()
        .from.systemProperties()
```

With YAML file having similar structure to the above:
```
DATABASE: foo.example.com
DATABASE_USER: john
DATABASE_PASS: doe
```

Sadly, the moment `DATABASE_PASS` or similar variable appears in the env, I get the following exception: 
```
Exception in thread "main" com.uchuhimo.konf.source.LoadException: fail to load DATABASE
	at com.uchuhimo.konf.source.SourceKt.loadItem(Source.kt:519)
	at com.uchuhimo.konf.source.SourceKt$load$1.invoke(Source.kt:532)
	at com.uchuhimo.konf.source.SourceKt$load$1.invoke(Source.kt)
	at com.uchuhimo.konf.BaseConfig.lock(BaseConfig.kt:65)
	at com.uchuhimo.konf.source.SourceKt.load(Source.kt:530)
	at com.uchuhimo.konf.BaseConfig.withSource(BaseConfig.kt:585)
	at com.uchuhimo.konf.source.DefaultLoaders.env(DefaultLoaders.kt:118)
	at example.server.ServerSpecKt.getApplicationConfig(ServerSpec.kt:41)
	at example.StarterAppKt.initializeApplicationContext(StarterApp.kt:43)
	at example.StarterAppKt.main(StarterApp.kt:68)
	at example.StarterAppKt.main(StarterApp.kt)
Caused by: com.uchuhimo.konf.source.ObjectMappingException: unable to map source com.uchuhimo.konf.ContainerNode@33c2bd in [type: system-environment] to value of type String
	at com.uchuhimo.konf.source.SourceKt.toValue(Source.kt:820)
	at com.uchuhimo.konf.source.SourceKt.loadItem(Source.kt:512)
	... 10 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:63)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3985)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2343)
	at com.uchuhimo.konf.source.SourceKt.toValue(Source.kt:815)
	... 11 more
```

Is there a mode to rely on simple naming without inferred nesting?

**Comment by uchuhimo** [comment]
There is no mode to disable inferred nesting, you can define a new source as a workaround. Here is an example:

```kotlin
fun envSource(): Source {
    return FlatSource(
        System.getenv().filter { (key, _) ->
            !(key.startsWith('.') || key.endsWith('.'))
        }.toSortedMap(),
        type = "system-environment",
        allowConflict = true
    )
}

Config {
    addSpec(Root)
}
        .from.yaml.resource("server.yml")
        .withSource(envSource())
        .from.systemProperties()
```

**Comment by golx** [comment]
@uchuhimo thanks! your workaround worked for me. 
Any plans to add such functionality in the future? This could help those like me who would want to introduce `konf` with minimal impact to their existing infrastructure. 

In any case, this ticket can now be closed.

**Comment by DanySK** [comment]
I hit the same issue as well. In my case, it's a TOML configuration of the kind:

```toml

[ arbitraryname1 ]
description = "..."

[ arbitraryname1.configuration ]
...

[ arbitraryname1.expectations ]
...
```

there are several entries with arbitrary prefixes

**Comment by uchuhimo** [comment]
@DanySK Would you like to provide a minimal code snippet of your `ConfigSpec` and `Config` for me to debug?

**Comment by uchuhimo** [comment]
@golx I have added this feature in [v0.22.0](https://github.com/uchuhimo/konf/releases/tag/v0.22.0). You can use the following code to achieve the same purpose:

```kotlin
Config {
    addSpec(Root)
}.from.env(nested=false)
```

**Comment by golx** [comment]
Thanks! We'll give it a try.
