### ISSUE TITLE
java.lang.IllegalAccessError: tried to access class com.moandjiezana.toml.ValueWriter from class com.moandjiezana.toml.Toml4jValueWriters

### ISSUE THREAD

**Issue by Cubxity** [uchuhimo/konf#63]
**Stacktrace**
```
java.lang.IllegalAccessError: tried to access class com.moandjiezana.toml.ValueWriter from class com.moandjiezana.toml.Toml4jValueWriters
  at com.moandjiezana.toml.Toml4jValueWriters.<clinit>(Toml4jWriter.kt:98) ~[?:?]
  at com.moandjiezana.toml.Toml4jWriter.write(Toml4jWriter.kt:73) ~[?:?]
  at com.moandjiezana.toml.Toml4jWriter.write(Toml4jWriter.kt:56) ~[?:?]
  at com.uchuhimo.konf.source.toml.TomlWriter.toText(TomlWriter.kt:42) ~[?:?]
  at com.uchuhimo.konf.source.toml.TomlWriter.toWriter(TomlWriter.kt:32) ~[?:?]
  at com.uchuhimo.konf.source.toml.TomlWriter.toOutputStream(TomlWriter.kt:37) ~[?:?]
  at com.uchuhimo.konf.source.Writer$DefaultImpls.toFile(Writer.kt:49) ~[?:?]
  at com.uchuhimo.konf.source.toml.TomlWriter.toFile(TomlWriter.kt:28) ~[?:?]
```

**JVM Version:** 1.8.0_212
**konf version:** 1.0.0

This was run using `itzg/bungeecord` docker image.

**Comment by Cubxity** [comment]
This was fixed by relocating toml since it conflicted with Velocity
